# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b5fe03118aa6052f54ac03d10144ef36e8ffae734eaa9f8a3a2d3e188aa79006db25a905811b24fbfd6b12dd6d4b5943407b371d5bcd183b3a047ea2288d02

test:
  secret_key_base: 8828db9bc147ae79cae024868c2deb39d7996086229796f57dceef06c93433b8b355f77305a59296a2eabb012e00934f825668f6fafa1c475bf56469d121168b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
