# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c02fce0d26de111c0959e1d58a759a46f6199494af123ba1e989cae267cb5868f998e5686144a0889967e099d62feb256c76966893922a62e643e6669ff8a1

test:
  secret_key_base: d99de6ddacde6341769f65cf710d12ac428eef1a688ac1255be5c9d2bf3cea731ee6b469995d74e7644564a94c6e8f9a8568d96d939bf67f6f050382b274c9e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
